ENDPOINT ="jobby.czkaa4kseikm.us-east-1.rds.amazonaws.com" 
DATABASE = "postgres"
USERNAME="jobby"
PASSWORD="12345678"
PORT="5432"
DATABASE_URL = f"postgresql+psycopg2://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASE}"