ENDPOINT ="******************************" 
DATABASE = "***************"
USERNAME="************"
PASSWORD="************"
PORT="************"
DATABASE_URL = f"host='{ENDPOINT}' dbname='{DATABASE}' user='{USERNAME}' password='{PASSWORD}' port='{PORT}'"